# Scipy 

#### SciPy, pronounced as Sigh Pi, is a scientific python open source, distributed under the BSD licensed library to perform Mathematical, Scientific and Engineering Computations. The SciPy library depends on NumPy, which provides convenient and fast N-dimensional array manipulation. The SciPy library is built to work with NumPy arrays and provides many user-friendly and efficient numerical practices such as routines for numerical integration and optimization. Together, they run on all popular operating systems, are quick to install and are free of charge. NumPy and SciPy are easy to use, but powerful enough to depend on by some of the world's leading scientists and engineers.

#### https://scipy-lectures.org/
###        


In [1]:
import numpy as np

In [2]:
print(np.linspace(1., 4., 6))

[1.  1.6 2.2 2.8 3.4 4. ]


####       

###  K-Means Implementation in SciPy

In [3]:
from scipy.cluster.vq import kmeans,vq,whiten

In [4]:
from numpy import vstack,array

In [5]:
from numpy.random import rand

In [9]:
# data generation with three features

data = vstack((rand(10,3) + array([.5,.5,.5]),rand(10,3)))

In [10]:
print(data)

[[0.56277681 1.19659178 0.60540895]
 [1.26421834 0.81194724 1.38870664]
 [0.86505706 1.22780865 0.90811355]
 [0.62989644 0.79625693 1.03868249]
 [1.00665654 1.45942954 0.6452284 ]
 [1.20964196 1.25095695 0.57920503]
 [0.81717673 0.72529366 0.78966626]
 [1.11642976 0.98273137 1.43723891]
 [1.30126959 0.95857326 0.63929221]
 [0.66148249 0.58562988 0.74421793]
 [0.57672869 0.34354002 0.9727458 ]
 [0.04352153 0.77322205 0.08772268]
 [0.29820736 0.72949779 0.89310292]
 [0.98111331 0.31620395 0.86024269]
 [0.58753038 0.60794963 0.7384155 ]
 [0.95257998 0.00154525 0.43878064]
 [0.62118288 0.81725821 0.94028651]
 [0.6680299  0.75252111 0.55698188]
 [0.86444286 0.40855456 0.09570056]
 [0.27519482 0.50981657 0.22144367]]


In [11]:
# whitening of data for normalizing

data = whiten(data)

In [12]:
print(data)

[[1.71004197 3.43746053 1.72849746]
 [3.84142772 2.33248851 3.9648834 ]
 [2.62854451 3.52713752 2.59274656]
 [1.91399029 2.28741481 2.96553272]
 [3.05880575 4.19251705 1.8421856 ]
 [3.67559307 3.59363585 1.65368289]
 [2.48305633 2.08355795 2.25456879]
 [3.39236038 2.82310169 4.10344744]
 [3.95401089 2.75370247 1.82523725]
 [2.00996703 1.68234448 2.12480968]
 [1.75243587 0.98689065 2.77727749]
 [0.13224361 2.22124229 0.25045622]
 [0.90612671 2.0956352  2.54988982]
 [2.98119062 0.90836207 2.4560709 ]
 [1.78525767 1.74646264 2.10824322]
 [2.89448983 0.00443905 1.25275853]
 [1.88751345 2.34774539 2.68460328]
 [2.02986185 2.16177451 1.59023379]
 [2.62667819 1.17365856 0.27323377]
 [0.83620129 1.46455489 0.63224178]]


In [15]:
# computing K-Means with K = 3 (2 clusters)

centroids,_ = kmeans(data,7)

In [16]:
print("Centroids:\n",centroids)

Centroids:
 [[3.61689405 2.5777951  4.03416542]
 [3.81480198 3.17366916 1.73946007]
 [2.93784022 0.45640056 1.85441471]
 [1.84602615 1.9239782  2.38189485]
 [0.48422245 1.84289859 0.441349  ]
 [2.46579741 3.71903837 2.05447654]
 [2.62667819 1.17365856 0.27323377]]


In [17]:
# assign each sample to a cluster

clx,_ = vq(data,centroids)

In [18]:
print("Cluster:\n",clx)

Cluster:
 [5 0 5 3 5 1 3 0 1 3 3 4 3 2 3 2 3 3 6 4]


In [19]:
#Fast Fourier Transform
#Importing the fft and inverse fft functions from fftpackage

from scipy.fftpack import fft

In [20]:
#create an array with random n numbers

x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])

In [21]:
y = fft(x)

In [22]:
print("FFT :\n",y)

FFT :
 [ 4.5       -0.j          2.08155948-1.65109876j -1.83155948+1.60822041j
 -1.83155948-1.60822041j  2.08155948+1.65109876j]


In [23]:
from scipy.fftpack import ifft

In [24]:
yinv = ifft(y)

In [25]:
print("FFT Inverse:\n",yinv)

FFT Inverse:
 [ 1. +0.j  2. +0.j  1. +0.j -1. +0.j  1.5+0.j]


In [26]:
#Discrete Cosine Transform

from scipy.fftpack import dct
print ("DCT:\n",dct(np.array([4., 3., 5., 10., 5., 3.])))

DCT:
 [ 60.          -3.48476592 -13.85640646  11.3137085    6.
  -6.31319305]


In [27]:
#Inverse Discrete Cosine Transform

from scipy.fftpack import idct
print("IDCT:\n",idct(np.array([4., 3., 5., 10., 5., 3.])))

IDCT:
 [ 39.15085889 -20.14213562  -6.45392043   7.13341236   8.14213562
  -3.83035081]


##      

# SciPy - Integrate

#### The general form of quad is scipy.integrate.quad(f, a, b), Where ‘f’ is the name of the function to be integrated. Whereas, ‘a’ and ‘b’ are the lower and upper limits, respectively.
#### f(x) = (ex)^2

##### Let us see an example of the Gaussian function, integrated over a range of 0 and 1.

# ∫f(x)dx

In [29]:
# Single Integration
# quad()

import scipy.integrate
from numpy import exp
f= lambda x:exp(-x**2)
i = scipy.integrate.quad(f,0,1)

In [32]:
i

(0.7468241328124271, 8.291413475940725e-15)

#    

# Linear Algebra

#### x + 3y + 5z = 10
#### 2x + 5y + z = 8
####            2x + 3y + 8z = 3

In [33]:
#importing the scipy and numpy packages

from scipy import linalg
import numpy as np

In [36]:
#Declaring the numpy arrays
#a = np.array([[x, 3y, 5z], [2x, 5y, z], [2x, 3y, 8z]])
#b = np.array([10, 8, 3])

a = np.array([[1, 3, 5], [2, 5, 1], [2, 3, 8]])
b = np.array([10, 8, 3])

In [37]:
X=  linalg.solve(a, b)

In [40]:
print(X)

[-9.28  5.16  0.76]


In [49]:
# Compute the inverse of a matrix.

a = np.array([[1., 2.], [3., 4.]])
linalg.inv(a)
array([[-2. ,  1. ], [ 1.5, -0.5]])
np.dot(a, linalg.inv(a))
array([[ 1.,  0.], [ 0.,  1.]])

array([[1., 0.],
       [0., 1.]])

In [47]:
print(X)

[[-2.   1. ]
 [ 1.5 -0.5]]


# Finding a Determinant

In [44]:
#Declaring the numpy array
A = np.array([[1,2],[3,4]])

#Passing the values to the det function
x = linalg.det(A)

In [50]:
print(x)

-2.0


#  Eigenvalues and Eigenvectors

# Image Processing

In [52]:
from scipy import misc

In [55]:
f = misc.face()

In [56]:
misc.imsave('face.png', f) # uses the Image module (PIL)

AttributeError: module 'scipy.misc' has no attribute 'imsave'